default_platform(:android)

platform :android do
  desc "Upload a new canary build"
  lane :uploadCanary do
    # Building the AAB and preparing metadata is done by 🦄 Unicorn
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/scRelease/app-sc-release.aab"
    )
  end

  desc "Upload a new beta build"
  lane :uploadBeta do
    # Building the AAB and metadata preparation is done externally.
    upload_to_play_store(
      track: "beta",
      release_status: "draft",
      aab: "../build/app/outputs/bundle/scRelease/app-sc-release.aab"
    )
  end
end
