name: api
description: A client-side wrapper around the HPI Schul-Cloud API.
version: 0.0.1
homepage: https://github.com/hpi-schul-cloud/schulcloud-flutter/tree/main/api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  dartx: ^0.6.0
  dio: ^4.0.0-beta7
  enum_to_string: ^2.0.0-nullsafety.1
  freezed_annotation: ^0.14.0
  intl: ^0.17.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  oxidized: ^4.0.0
  rxdart: ^0.26.0
  supercharged_dart: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.5
  extra_pedantic: ^1.3.0
  freezed: ^0.14.0
  json_serializable: ^4.0.2
  test: ^1.16.7

dependency_overrides:
  # TODO(JonasWanke): remove these when build_runner updates its dependencies
  http_multi_server: ^3.0.0
  io: ^1.0.0
  shelf_web_socket: ^1.0.0
  web_socket_channel: ^2.0.0
